### ISSUE TITLE
test_mul.m error for bigger matrix

### ISSUE THREAD

**Issue by michalkvasnicka** [philipheinisch/MatCL#1]
When I increase size of matrices A and B from 15000 to 20000 see line 10 I always got the following error message:

Exception:
ERROR: clEnqueueNDRangeKernel
Unexpected Standard exception from MEX file.
What() is:clEnqueueReadBuffer
..

Error in test_mul (line 50)
[run_time]=cl_run_kernel(1,'MM',Range,0,A,B,C,[1 1 2]);

With CUDA is everything OK:
Ac = gpuArray(A);
Bc = gpuArray(B);
mCc = Ac*Bc;
mC = gather(mCc);

so this is not memory problem with current GPU (Device:  GeForce GTX TITAN)

**Comment by philipheinisch** [comment]
This is most likely an issue related to the host memory/system or the GTX Titan OpenCL driver, as large matrices run without problem even on a GTX 1060 or a Radeon R9 290. As MEX memory handling can be quite inefficient it is possible that not enough host memory is available. As the Matlab CUDA interface does not rely on MEX, the memory handling is more efficient.

**Comment by michalkvasnicka** [comment]
I have 32GB RAM on may Linux workstation, which should be more than enough for these matrices. GTX Titan has 6GB RAM, which is still enough I think.

**Comment by philipheinisch** [comment]
Considering that this example uses double precision and the kernel needs some local variables, 6GB might be at the limit of what is necessary on the GPU. Especially as the OpenCL memory management tends to be less efficient than CUDA to preserve cross platform portability. However, as it turns out this is probably related to the way NVidia uses CL_DEVICE_MAX_MEM_ALLOC_SIZE (see https://devtalk.nvidia.com/default/topic/992502/why-is-cl_device_max_mem_alloc_size-never-larger-than-25-of-cl_device_global_mem_size-only-on-nvidia-/). We added a warning if CL_DEVICE_MAX_MEM_ALLOC_SIZE is exceeded, but if this is related to the allocation limit, it has to be fixed by NVidia.
